<?php

/**
 * @file
 * Provides a feedback entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function guestbook_entity_theme(): array {
  return [
    'kay_feedback' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for feedback templates.
 *
 * Default template: kay-feedback.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the feedback information and
 *   any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_kay_feedback(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
